apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
data:
  keycloak-url: keycloak-service
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  KEYCLOAK_USER: YWRtaW4= #admin
  KEYCLOAK_PASSWORD: cGFzcw== #pass
  DB_USER: a2V5Y2xvYWtfdXNlcg== #keycloack_user
  DB_PASSWORD: a2V5Y2xvYWtfcGFzcw== #keycloack_pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:16.1.1
          ports:
            - containerPort: 8080
              name: web-http
            - containerPort: 8443
              name: web-https
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          env:
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_DATABASE
              value: "<database_name>"
            - name: DB_SCHEMA
              value: "keycloak"
            - name: DB_ADDR
              value: "<database_address>"
            - name: DB_PORT
              value: "<database_port>"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KEYCLOAK_FRONTEND_URL
              value: "<keycloak_frontend_url>/auth"
          envFrom:
            - secretRef:
                name: keycloak-secret
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - name: web-http
      protocol: TCP
      port: 6000
      targetPort: web-http
      nodePort: 30150
    - name: web-https
      protocol: TCP
      port: 6001
      targetPort: web-https
      nodePort: 30151
