apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-db-config
data:
  mongo-db-url: mongo-db-service
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secret
type: Opaque
data:
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
spec:
  selector:
    matchLabels:
      app: mongo-db # has to match .spec.template.metadata.labels
  serviceName: mongo-db-service
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mongo-db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo-db
          image: mongo:4.4
          args:
            - "--nojournal"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-db-data
              mountPath: /data/db
      volumes:
        - name: mongo-db-data
          persistentVolumeClaim:
            claimName: mongo-db-data
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db-service
spec:
  type: ClusterIP
  selector:
    app: mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
