apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq-port: "8300"
  rabbitmq-url: rabbitmq-service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq-service
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - containerPort: 5672
              name: communication
            - containerPort: 15672 #web management
              name: web-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: mamma-secret
                  key: rabbitmq-user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: mamma-secret
                  key: rabbitmq-password
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq/
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: communication
      protocol: TCP
      port: 8300
      targetPort: communication
      nodePort: 30180
    - name: web-management
      protocol: TCP
      port: 8301
      targetPort: web-management
      nodePort: 30181
